### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_next_sibling'

### ISSUE THREAD

**Issue by DataThinkMonkey** [samuelbradshaw/python-scripture-scraper#1]
Python 3.11.3
Manjaro Linux 
Linux 5.10.181-2-MANJARO

```
Getting languages
Warning: Language “asf” is not recognized and will be ignored (most likely it was added to Church content recently). To include this language, add it to the language mappings in resources.py.
Found 140 languages

Gathering metadata: af / Afrikaans (Afrikaans)
Gathering metadata: am / አማርኛ (Amharic)
Gathering metadata: ar / العربية (Arabic)
Gathering metadata: ase / American Sign Language (ASL) (ASL)
Gathering metadata: ay / Aymar Aru (Aymara)
Gathering metadata: bg / Български (Bulgarian)
Gathering metadata: bi / Bislama (Bislama)
Gathering metadata: bik / Bikol (Bikolano)
Gathering metadata: bla / Nitsi’powahsin (Blackfoot)
Gathering metadata: bm / Bambara (Bambara)
Gathering metadata: bn / বাংলা (Bengali)
Gathering metadata: ca / Català (Catalan)
Gathering metadata: cag / Nivacle (Chulupi)
Gathering metadata: cak / Cakchiquel (Kaqchikel)
Gathering metadata: ceb / Cebuano (Cebuano)
Gathering metadata: ch / Chamoru (Chamorro)
Gathering metadata: chk / Fosun Chuuk (Chuukese)
Gathering metadata: cmn-Hans / 简体中文 - 普通话 (Simplified Chinese/Mandarin)
Gathering metadata: cmn-Hant / 繁體中文 - 國語 (Traditional Chinese/Mandarin
  )
Gathering metadata: cs / Česky (Czech)
Gathering metadata: cuk / Dulegaya (Kuna)
Gathering metadata: cy / Cymraeg (Welsh)
Gathering metadata: da / Dansk (Danish)
Gathering metadata: de / Deutsch (German)
Traceback (most recent call last):
  File "/home/jared/Projects/scripture-scraper/scrape.py", line 1042, in <module>
    main()
  File "/home/jared/Projects/scripture-scraper/scrape.py", line 89, in main
    gather_metadata_for_language(language)
  File "/home/jared/Projects/scripture-scraper/scrape.py", line 282, in gather_metadata_for_language
    verse_range_separator_example = footnotes.select_one('#note1d_p1 a').find_next_sibling('a').text  # 'Mosiah 1:2–3'
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_next_sibling'
```

**Comment by samuelbradshaw** [comment]
Good find – fixed! It looks like the IDs for footnotes in German content are slightly different from other languages.
I also fixed the missing language warning.
